input_size: 224
batch_size: 128
seed: 0
max_epochs: 100
patience: 10
replicates: 5
n_workers: 0
val_size: 0.1
learning_rate: 0.001
weight_decay: 0.01
# train_data_dir: '../relabel_20230110_norare'
train_data_dir: '../../../../../imgs/relabel_20230110_norare'
exts: [jpg, tiff]
classes: [aggregate, bubble, fiber_blur, fiber_sharp, long_pellet,
          mini_pellet, noise, short_pellet, swimmer]
train_domains: [RR, SRT, FK, JC]
domain_splits_fname: domain_splits.json
train_data_stats_fname: train_data_stats.json
