input_size: 224
batch_size: 1024
model: 'resnet18'
mean: None
std: None
seed: 0
max_epochs: 100
patience: 10
replicates: 3
n_workers: 4
val_size: 0.1
learning_rate: 0.001
weight_decay: 0.01
data_dir: '../../../../../mnt/ssd-cluster/vinicius'
domain_splits_fname: domain_splits.json
classes: ['aggregate', 'bubble', 'fiber_blur', 'fiber_sharp', 'long_pellet', 'mini_pellet', 'noise', 'phyto_dino', 'phyto_long', 'phyto_round', 'rhizaria', 'salp_pellet', 'short_pellet', 'swimmer']
train_domains: ['SR', 'JC', 'FC', 'FO']
test_domain: 'RR'