device: 'cuda'
input_size: 224
batch_size: 1024
mean: [0.279, 0.304, 0.294]
std: [0.097, 0.102, 0.095]
pad: False
max_epochs: 100
patience: 10
n_workers: 4
learning_rate: 0.001
weight_decay: 0.01
data_dir: '../../mpic_data/imgs'
splits_fname: splits.json
classes: ['aggregate', 'bubble', 'fiber_blur', 'fiber_sharp', 'long_pellet', 'mini_pellet', 'noise', 'phyto_dino', 'phyto_long', 'phyto_round', 'rhizaria', 'salp_pellet', 'short_pellet', 'swimmer']
train_domains: ['SR', 'JC', 'FC', 'FO']